version: '3.1'
services:
  db:
    image: postgres
    restart: always
    network_mode: host
    environment:
      POSTGRES_USER: ${API_USER}
      POSTGRES_PASSWORD: ${API_PASSWORD}
      POSTGRES_DB: ${API_DATABASE}
