version: "3.1"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${API_USER}
      POSTGRES_PASSWORD: ${API_PASSWORD}
      POSTGRES_DB: ${API_DATABASE}
    ports:
      - 5432:5432

  db-test:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${API_USER}
      POSTGRES_PASSWORD: ${API_PASSWORD}
      POSTGRES_DB: ${API_DATABASE}
    ports:
      - 5433:5432
